version: '3'

services:

  elasticsearch:
    build: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    build: logstash/
    ports:
      - "5043:5043/udp"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build: kibana/
    volumes:
      - C:\Users\brabiller\Documents\logstash\kibana\config:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  apache:
    build: apache/
    ports:
      - "80:80"
    logging:
      driver: gelf
      options:
        gelf-address: "udp://10.0.75.0:5043"
    networks:
      - elk

networks:

  elk:
    driver: bridge